const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Project = require('./models/Project');

dotenv.config();

const connectDB = async () => {
  try {
    const conn = await mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/portfolio');
    console.log(`MongoDB Connected: ${conn.connection.host}`);
  } catch (error) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
};

const htmlCssProjects = [
  { name: "HTML Code Formatting", desc: "Improving HTML readability by organizing code structure and fixing indentation.", path: "https://rajyabdullah-spec.github.io/matrix-master-exercises/html-css-assignments/Assignment-1-Fix-Indentation", github: "https://github.com/rajyabdullah-spec/matrix-master-exercises/tree/main/html-css-assignments/Assignment-1-Fix-Indentation", techStack: ["HTML5", "CSS3", "Semantics"] },
  { name: "HTML Code Validation", desc: "Identifying and fixing syntax errors to ensure W3C web standards compliance.", path: "https://rajyabdullah-spec.github.io/matrix-master-exercises/html-css-assignments/Assignment-2-Code-Validation", github: "https://github.com/rajyabdullah-spec/matrix-master-exercises/tree/main/html-css-assignments/Assignment-2-Code-Validation", techStack: ["HTML5", "W3C Validation"] },
  { name: "Personal Website Foundations", desc: "Building a personal website from scratch using essential semantic HTML elements.", path: "https://rajyabdullah-spec.github.io/matrix-master-exercises/html-css-assignments/Assignment-3-Your-first-website", github: "https://github.com/rajyabdullah-spec/matrix-master-exercises/tree/main/html-css-assignments/Assignment-3-Your-first-website", techStack: ["HTML5", "Semantic Elements"] },
  { name: "Layout Repair & Box Model", desc: "Reconstructing layouts using CSS Box Model and Display properties without floats.", path: "https://rajyabdullah-spec.github.io/matrix-master-exercises/html-css-assignments/Assignment-4-The-Evil-Hacker", github: "https://github.com/rajyabdullah-spec/matrix-master-exercises/tree/main/html-css-assignments/Assignment-4-The-Evil-Hacker", techStack: ["CSS3", "Box Model"] },
  { name: "Classic Google UI Clone", desc: "Recreating the iconic 1998 Google interface with precise layout replication.", path: "https://rajyabdullah-spec.github.io/matrix-master-exercises/html-css-assignments/Assignment-5-Google", github: "https://github.com/rajyabdullah-spec/matrix-master-exercises/tree/main/html-css-assignments/Assignment-5-Google", techStack: ["HTML5", "CSS3", "Legacy UI"] },
  { name: "Twitter Login UI Redesign", desc: "Developing a modern, responsive login page focusing on UI and logo integration.", path: "https://rajyabdullah-spec.github.io/matrix-master-exercises/html-css-assignments/Assignment-6-Twitter", github: "https://github.com/rajyabdullah-spec/matrix-master-exercises/tree/main/html-css-assignments/Assignment-6-Twitter", techStack: ["CSS3", "Flexbox", "Responsive Design"] },
  { name: "Legacy Airbnb UI Clone", desc: "Recreating the 2009 Airbnb landing page using fixed-width layout techniques.", path: "https://rajyabdullah-spec.github.io/matrix-master-exercises/html-css-assignments/Assignment-7-AirBNB", github: "https://github.com/rajyabdullah-spec/matrix-master-exercises/tree/main/html-css-assignments/Assignment-7-AirBNB", techStack: ["CSS Layouts", "Positioning"] },
  { name: "Craigslist Legacy Layout", desc: "Building a multi-column layout with manual content organization.", path: "https://rajyabdullah-spec.github.io/matrix-master-exercises/html-css-assignments/Assignment-8-Craigslist", github: "https://github.com/rajyabdullah-spec/matrix-master-exercises/tree/main/html-css-assignments/Assignment-8-Craigslist", techStack: ["Multi-Column", "HTML Tables"] },
  { name: "Front-End Demo Challenge", desc: "Recreating the original 2001 PayPal landing page with clean HTML and CSS.", path: "https://rajyabdullah-spec.github.io/matrix-master-exercises/html-css-assignments/Demo-Challenge-paypal2002", github: "https://github.com/rajyabdullah-spec/matrix-master-exercises/tree/main/html-css-assignments/Demo-Challenge-paypal2002", techStack: ["HTML5", "CSS3", "Retro UI"] },
  { name: "Legacy LinkedIn Login UI", desc: "Replicating the 2008 LinkedIn login page focusing on clean code structure.", path: "https://rajyabdullah-spec.github.io/matrix-master-exercises/html-css-assignments/Front-End-Challenge-Linkedin", github: "https://github.com/rajyabdullah-spec/matrix-master-exercises/tree/main/html-css-assignments/Front-End-Challenge-Linkedin", techStack: ["HTML Forms", "Legacy UI"] },
  { name: "Materialize CSS Design", desc: "Replicating professional UI styling using Materialize CSS standards.", path: "https://rajyabdullah-spec.github.io/matrix-master-exercises/html-css-assignments/Assignment-9-The-Materialize", github: "https://github.com/rajyabdullah-spec/matrix-master-exercises/tree/main/html-css-assignments/Assignment-9-The-Materialize", techStack: ["Materialize CSS", "UI Frameworks"] },
  { name: "Bootstrap Personal Site", desc: "Modernizing a site using Bootstrap's grid system for mobile-first design.", path: "https://rajyabdullah-spec.github.io/matrix-master-exercises/html-css-assignments/Assignment-10-Time-to-Bootstrap", github: "https://github.com/rajyabdullah-spec/matrix-master-exercises/tree/main/html-css-assignments/Assignment-10-Time-to-Bootstrap", techStack: ["Bootstrap 5", "Grid System"] },
  { name: "Framework-Powered Redesign", desc: "Applying advanced Bootstrap components for a professional, responsive layout.", path: "https://rajyabdullah-spec.github.io/matrix-master-exercises/html-css-assignments/Assignment-11-Your-first-website-with-Framework", github: "https://github.com/rajyabdullah-spec/matrix-master-exercises/tree/main/html-css-assignments/Assignment-11-Your-first-website-with-Framework", techStack: ["Bootstrap 5", "UI Components", "Mobile-First"] }
];

const jsProjects = [
  { name: "Variables & Conditionals", desc: "Foundational logic: variables and conditionals.", path: "https://rajyabdullah-spec.github.io/vanilla-js-exercises/01-variables-and-conditionals/", github: "https://github.com/rajyabdullah-spec/vanilla-js-exercises/tree/main/01-variables-and-conditionals", techStack: ["JavaScript", "Variables", "Conditionals"] },
  { name: "Functions", desc: "Logic blocks and reusable functions.", path: "https://rajyabdullah-spec.github.io/vanilla-js-exercises/02-functions/", github: "https://github.com/rajyabdullah-spec/vanilla-js-exercises/tree/main/02-functions", techStack: ["JavaScript", "Functions", "Scope"] },
  { name: "Arrays & Loops", desc: "Iteration and data collections.", path: "https://rajyabdullah-spec.github.io/vanilla-js-exercises/03-arrays-and-loops/", github: "https://github.com/rajyabdullah-spec/vanilla-js-exercises/tree/main/03-arrays-and-loops", techStack: ["JavaScript", "Arrays", "Loops"] },
  { name: "Object Literals", desc: "Structured data using JS Objects.", path: "https://rajyabdullah-spec.github.io/vanilla-js-exercises/04-Objects/", github: "https://github.com/rajyabdullah-spec/vanilla-js-exercises/tree/main/04-Objects", techStack: ["JavaScript", "Objects", "Data Structures"] },
  { name: "Objects as Classes", desc: "OOP Principles and constructors.", path: "https://rajyabdullah-spec.github.io/vanilla-js-exercises/05-Objects-as-Classes/", github: "https://github.com/rajyabdullah-spec/vanilla-js-exercises/tree/main/05-Objects-as-Classes", techStack: ["JavaScript", "OOP", "Constructors"] },
  { name: "Window Object", desc: "Interactive exercise using Browser APIs.", path: "https://rajyabdullah-spec.github.io/vanilla-js-exercises/06-Window-Object/", github: "https://github.com/rajyabdullah-spec/vanilla-js-exercises/tree/main/06-Window-Object", techStack: ["JavaScript", "BOM", "Browser Events"] },
  { name: "DOM Manipulation", desc: "Live UI interaction and DOM events.", path: "https://rajyabdullah-spec.github.io/vanilla-js-exercises/07-DOM-Manipulation/", github: "https://github.com/rajyabdullah-spec/vanilla-js-exercises/tree/main/07-DOM-Manipulation", techStack: ["JavaScript", "DOM API", "Event Listeners"] },
  { name: "Interactive Task Manager", desc: "Comprehensive project with JS logic and Bootstrap.", path: "https://rajyabdullah-spec.github.io/vanilla-js-exercises/08-Bring-everything-together/", github: "https://github.com/rajyabdullah-spec/vanilla-js-exercises/tree/main/08-Bring-everything-together", techStack: ["JavaScript", "DOM", "Bootstrap", "CRUD"] },
  { name: "Advanced DOM", desc: "Practicing event listeners and real-time element replacement.", path: "https://rajyabdullah-spec.github.io/vanilla-js-exercises/09-DOM-Manipulation/", github: "https://github.com/rajyabdullah-spec/vanilla-js-exercises/tree/main/09-DOM-Manipulation", techStack: ["JavaScript", "Event Delegation", "UI Nodes"] },
  { name: "The JS Calculator", desc: "Fully functional calculator with chained operations.", path: "https://rajyabdullah-spec.github.io/vanilla-js-exercises/10-The-Calculator/", github: "https://github.com/rajyabdullah-spec/vanilla-js-exercises/tree/main/10-The-Calculator", techStack: ["JavaScript", "Math Logic", "DOM State"] },
  { name: "ES6 Fundamentals", desc: "Advanced ES6 Scoping, Destructuring, and Spread.", path: "https://rajyabdullah-spec.github.io/vanilla-js-exercises/11-ES6-Exercises/", github: "https://github.com/rajyabdullah-spec/vanilla-js-exercises/tree/main/11-ES6-Exercises", techStack: ["JavaScript", "ES6+", "Destructuring"] },
  { name: "Array Processing", desc: "Advanced manipulation of data collections using filter, map, and reduce.", path: "https://rajyabdullah-spec.github.io/vanilla-js-exercises/12-Array-Processing-Exercises/", github: "https://github.com/rajyabdullah-spec/vanilla-js-exercises/tree/main/12-Array-Processing-Exercises", techStack: ["JavaScript", "Array Methods", "Map Filter Reduce"] },
  { name: "Functions Logic", desc: "Mastering arrow functions, object methods, and logical operators for cleaner code.", path: "https://rajyabdullah-spec.github.io/vanilla-js-exercises/13-Functions-Logic/", github: "https://github.com/rajyabdullah-spec/vanilla-js-exercises/tree/main/13-Functions-Logic", techStack: ["JavaScript", "Arrow Functions", "Logic"] },
  { name: "Advanced Pomodoro Clock", desc: "A high-performance productivity tool featuring automated session switching, long-press controls, and a dynamic Glassmorphism UI.", path: "https://rajyabdullah-spec.github.io/vanilla-js-exercises/14-Pomodoro-Clock/", github: "https://github.com/rajyabdullah-spec/vanilla-js-exercises/tree/main/14-Pomodoro-Clock", techStack: ["JavaScript", "JS Timers", "Glassmorphism"] },
  { name: "OOP & Async Integration", desc: "Advanced architecture using ES6 Classes, Context binding (this), and Promise-based asynchronous logic.", path: "https://rajyabdullah-spec.github.io/vanilla-js-exercises/15-OOP-Putting-Everything-Together/", github: "https://github.com/rajyabdullah-spec/vanilla-js-exercises/tree/main/15-OOP-Putting-Everything-Together", techStack: ["JavaScript", "ES6 Classes", "Promises", "Async/Await"] }
];

const algoProjects = [
  { name: "Basic JS Algorithms", desc: "Mastering fundamental loops (1-135) and T-Diagram analysis for Sum, Max, and Average.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/01-Basic-Algorithms/Monday-Basic.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Loops", "T-Diagrams"] },
  { name: "Logic Patterns", desc: "Practice advanced logic patterns including Fibonacci sequence and FizzBuzz challenges.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/01-Basic-Algorithms/Tuesday-Logic.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Fibonacci", "FizzBuzz"] },
  { name: "Factorialize!", desc: "Calculating the product of all positive integers up to n, ensuring 0! equals 1.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/01-Basic-Algorithms/Wednesday-Factorial.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Factorial", "Edge Cases"] },
  { name: "Palindrome Checker", desc: "Verifying if a string reads the same forwards and backwards by comparing opposite indices.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/01-Basic-Algorithms/Thursday-Palindrome.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Strings", "Two Pointers"] },
  { name: "3rd Highest Number", desc: "Finding the third-largest value in an array using maximum efficiency (O(n)) in a single pass.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/01-Basic-Algorithms/Friday-ThirdHighest.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Arrays", "O(n) Efficiency"] },
  { name: "Largest Number in Arrays", desc: "Extracting the maximum value from nested multi-dimensional arrays using optimized dual-iteration loops.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/02-Intermediate-Algorithms/Monday-LargestNumbers.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Nested Arrays", "Max Finding"] },
  { name: "Find the Longest Word", desc: "Analyzing text strings, splitting them into individual elements using string methods, and dynamically tracking maximum length boundaries.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/02-Intermediate-Algorithms/Tuesday-LongestWord.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "String Split", "Max Length"] },
  { name: "Title Case a Sentence", desc: "An intermediate algorithm that processes sentences to capitalize the first letter of each word and lowercase the rest, engineered with an embedded T-Diagram for verification.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/02-Intermediate-Algorithms/Wednesday-TitleCase.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "String Manipulation", "Regex"] },
  { name: "Sum All Numbers in a Range", desc: "Calculates the sum of a numerical range using two paradigms: a linear iterative loop O(n) and Gauss's arithmetic progression formula O(1), both documented with structural execution flow trace tables.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/02-Intermediate-Algorithms/thursday-sum-all-numbers-in-a-range.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "O(n) vs O(1)", "Gauss Formula"] },
  { name: "Fibonacci Sequence (n-th Term)", desc: "Calculating the n-th Fibonacci number using clean dynamic state tracking, completely documented with numerical trace sequences.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/02-Intermediate-Algorithms/Friday-Fibonacci.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Dynamic State", "Sequences"] },
  { name: "Game of 3s", desc: "Implementing the dynamic math game logic, dividing by 3 or adding/subtracting 1 to reach parity, fully traced with operational states.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/03-Professional-Algorithms/Monday-GameOfThree.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Math Operations", "State Tracing"] },
  { name: "Magic Squares", desc: "Analyzing 3x3 matrix alignment configurations, verifying uniform parity balances across rows, columns, and primary diagonal vectors equal to 15.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/03-Professional-Algorithms/Tuesday-MagicSquares.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "3x3 Matrix", "Vector Analysis"] },
  { name: "Search and Replace", desc: "Executing contextual string alterations while explicitly preserving case configurations via structural slicing and multi-paradigm verification mapping.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/03-Professional-Algorithms/wednesday-search-replace.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Context Search", "Case Preservation"] },
  { name: "Sum All Primes", desc: "Aggregating sequential prime integer subsets by implementing a highly efficient inner loop restricted to an optimized square root boundary sequence.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/03-Professional-Algorithms/Thursday-SumAllPrimes.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Primes", "Loop Optimization"] },
  { name: "Sum All Odd Fibonacci", desc: "Generating Fibonacci series limits and safely filtering odd integer totals using custom modular logic boundaries and dual structural paradigms.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/03-Professional-Algorithms/friday-sum-odd-fibonacci.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Fibonacci Filters", "Modulo Logic"] },
  { name: "Bubble Sort Challenge", desc: "Implementing the core numerical bubble sorting mechanism using traditional double-nested loops and modern ES6 optimized early-exit flags.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/04-sorting-algorithms/monday-bubble-sort.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Bubble Sort", "Nested Loops"] },
  { name: "Selection Sort Challenge", desc: "Repeated minimum index finding via linear scanning and execution of elements swapping using traditional variables and advanced ES6 destructured paradigms.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/04-sorting-algorithms/tuesday-selection-sort.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Selection Sort", "Min Index Scan"] },
  { name: "rFactorial vs iFactorial", desc: "Calculating numerical factorials through two distinct computer science computational methods: memory efficient iterative loops and functional call stack winding recursion.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/05-recursion-algorithms/monday-factorial.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Recursion", "Call Stack"] },
  { name: "Bunny Ears Challenge", desc: "Computing total floppy ears across linear bunny collections recursively without loops or multiplication, visualizing functional stack depth accumulation.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/05-recursion-algorithms/tuesday-bunny-ears.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Stack Accumulation", "No Loops"] },
  { name: "Power N", desc: "Computing base to the n power recursively without using loops, visualizing functional structural execution flow.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/05-recursion-algorithms/wednesday-powern.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Recursive Winding", "Math"] },
  { name: "iFib vs rFib", desc: "Define both iterative and recursive methods that return the nth Fibonacci number synchronized with required test specification bounds.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/05-recursion-algorithms/thursday-fibonacci.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Recursive Fibonacci", "Iterative Sync"] },
  { name: "r Triangle", desc: "Compute recursively the total number of blocks in a triangle with given rows through stack aggregation and sequential workflows.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/05-recursion-algorithms/friday-triangle.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "Triangle Blocks", "Recursion"] },
  { name: "Demo Algorithm Challenge", desc: "Comprehensive review pipeline solving in-place array reversing, custom recursive array filtering, selection sort logic, and sub-array maximum scans under constraints.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/06-Challenges/demo-algorithm-challenge.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "In-Place Reverse", "Sub-Array Scans"] },
  { name: "Official Algorithms Challenge", desc: "The official assessment architecture. Features exclusive XOR divisibility filters, Fibonacci limit loops, and custom dual-pointer string validation.", path: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery/blob/main/06-Challenges/AlgorithmsChallenge.js", github: "https://github.com/rajyabdullah-spec/JavaScript-Algorithms-Mastery", techStack: ["Algorithms", "XOR Filters", "Dual Pointers"] }
];

const ajaxProjects = [
  { name: "Tenor GIF Fetch API", desc: "Live GIF search engine using classic XMLHttpRequest (XHR) architecture, JSON parsing, and dynamic DOM injection.", path: "https://rajyabdullah-spec.github.io/ajax-api-applications/project-16-tenor-gif/", github: "https://github.com/rajyabdullah-spec/ajax-api-applications/tree/main/project-16-tenor-gif", techStack: ["AJAX", "XHR", "Tenor API", "JSON Parsing"] },
  { name: "CineTrack - Movie Dashboard", desc: "Production-grade asynchronous search engine interfacing with OMDb API, featuring custom secure state loading and try-catch error traps.", path: "https://rajyabdullah-spec.github.io/ajax-api-applications/project-17-cinetrack-movies/", github: "https://github.com/rajyabdullah-spec/ajax-api-applications/tree/main/project-17-cinetrack-movies", techStack: ["AJAX", "Fetch API", "OMDb API", "Async Search"] },
  { name: "SkyCast - Weather Dashboard", desc: "Live global weather metrics station built on OpenWeatherMap API with secure unit switching configurations and adaptive interface contrast.", path: "https://rajyabdullah-spec.github.io/ajax-api-applications/project-18-skycast-weather/", github: "https://github.com/rajyabdullah-spec/ajax-api-applications/tree/main/project-18-skycast-weather", techStack: ["AJAX", "OpenWeather API", "Async/Await"] },
  { name: "StoreCraft - E-Commerce", desc: "Modern catalog powered by FakeStoreAPI utilizing full application state memory counters and zero-latency array local search filters.", path: "https://rajyabdullah-spec.github.io/ajax-api-applications/project-19-storecraft-ecommerce/", github: "https://github.com/rajyabdullah-spec/ajax-api-applications/tree/main/project-19-storecraft-ecommerce", techStack: ["AJAX", "FakeStore API", "Array Filters"] },
  { name: "NASA Exploration Space", desc: "Planetary exploration dashboard tracking NASA APOD API with polymorphic layout rendering supporting responsive Bootstrap context iFrames.", path: "https://rajyabdullah-spec.github.io/ajax-api-applications/project-20-nasa-explorers/", github: "https://github.com/rajyabdullah-spec/ajax-api-applications/tree/main/project-20-nasa-explorers", techStack: ["AJAX", "NASA APOD API", "REST API"] }
];

const backendProjects = [
  { id: "01", name: "Express.js & EJS Foundations", desc: "Mastering core backend basics: server initialization, routing pipelines, custom middleware usage (Morgan logger), static file serving, and dynamic page rendering via EJS template engines.", path: "https://github.com/rajyabdullah-spec/node-backend-playground/tree/main/01-express-ejs-basics", github: "https://github.com/rajyabdullah-spec/node-backend-playground", techStack: ["Node.js", "Express.js", "EJS", "Morgan Middleware"] },
  { id: "02", name: "The Timeline: In-Memory Data", desc: "First iteration of the timeline application. Implemented algorithmic data processing to handle local structures and sort user feeds in a strict reverse-chronological sequence without database dependencies.", path: "https://github.com/rajyabdullah-spec/node-backend-playground/tree/main/02-the-timeline", github: "https://github.com/rajyabdullah-spec/node-backend-playground", techStack: ["Node.js", "Express.js", "In-Memory Feed"] },
  { id: "03", name: "The Timeline: Cloud MVC Architecture", desc: "Transitioning the monolith into a full Model-View-Controller (MVC) design pattern. Integrated MongoDB Atlas cloud database via Mongoose ODM to execute secure CRUD operations and rigid schema validations.", path: "https://github.com/rajyabdullah-spec/node-backend-playground/tree/main/03-the-timeline-v2", github: "https://github.com/rajyabdullah-spec/node-backend-playground", techStack: ["Node.js", "Express.js", "MongoDB", "MVC Pattern"] },
  { id: "04", name: "The Timeline: Relational Sub-Resources", desc: "Advanced backend iteration mapping relational database architectures. Engineered a secondary sub-collection schema for user comments using ObjectId references, backed by automated cascading depletions.", path: "https://github.com/rajyabdullah-spec/node-backend-playground/tree/main/04-the-timeline-v3", github: "https://github.com/rajyabdullah-spec/node-backend-playground", techStack: ["Node.js", "Express.js", "MongoDB", "Relational Schemas"] },
  { id: "05", name: "The Timeline: Headless REST API Engine", desc: "Final transition into a clean headless backend infrastructure. Decoupled frontend renderings entirely to deliver pure JSON payloads, mapped standard HTTP status response codes, and verified operations using Postman.", path: "https://github.com/rajyabdullah-spec/node-backend-playground/tree/main/05-the-timeline-v4", github: "https://github.com/rajyabdullah-spec/node-backend-playground", techStack: ["Node.js", "Express.js", "MongoDB", "REST API"], images: ["https://raw.githubusercontent.com/rajyabdullah-spec/node-backend-playground/main/05-the-timeline-v4/assets/get-posts-200.gif"] },
  { id: "06", name: "The Timeline: Secure JWT Full-Stack", desc: "The production milestone of the timeline. Engineered a complete secure session infrastructure using JSON Web Tokens (JWT) cookies, custom authentication walls, environment variable masking (.env), virtual populate, and UI layout scroll memory preservation.", path: "https://timeline-api-v4.onrender.com", github: "https://github.com/rajyabdullah-spec/node-backend-playground/tree/main/06-the-timeline-v5", techStack: ["Node.js", "Express.js", "MongoDB", "JWT Auth", "HTTP-Only Cookies"] },
  { id: "07", name: "NYT MVC Architecture", desc: "A complete Full-Stack MVC application with strict backend validation, isolated EJS views, and MongoDB Atlas cloud integration.", path: "https://github.com/rajyabdullah-spec/node-backend-playground/tree/main/07-demo-challenge-one", github: "https://github.com/rajyabdullah-spec/node-backend-playground", techStack: ["Node.js", "Express.js", "MongoDB", "EJS Views"], singleGif: { url: "https://raw.githubusercontent.com/rajyabdullah-spec/node-backend-playground/main/07-demo-challenge-one/assets/project-demo.gif" } },
  { id: "08", name: "Welcome App MVC", desc: "A secure, highly-tuned Welcome App engineered using full-stack Node.js MVC architecture, custom routing pipelines, encrypted database storage, and fluid UI interfaces.", path: "https://github.com/rajyabdullah-spec/node-backend-playground/tree/main/08-demo-challenge-two", github: "https://github.com/rajyabdullah-spec/node-backend-playground", techStack: ["Node.js", "Express.js", "MongoDB", "Bcrypt Hashing"], singleGif: { url: "https://raw.githubusercontent.com/rajyabdullah-spec/node-backend-playground/main/08-demo-challenge-two/assets/Demo2.gif" } },
  { id: "09", name: "The Facebook MVC Challenge", desc: "A production-grade server-side micro-platform strictly enforcing MVC architecture, standalone custom routing paths, automated client deletion checks, and strict database field length restrictions.", path: "https://github.com/rajyabdullah-spec/node-backend-playground/tree/main/09-The-Challenge-The-Facebook", github: "https://github.com/rajyabdullah-spec/node-backend-playground", techStack: ["Node.js", "Express.js", "MongoDB", "Full-Stack MVC"], singleGif: { url: "https://raw.githubusercontent.com/rajyabdullah-spec/node-backend-playground/main/09-The-Challenge-The-Facebook/assets/The-Challenge.gif" } }
];

const reactProjects = [
  { name: "Core Layout Framework", desc: "Demonstrates standard foundational initialization of React architecture, applying clean component modularization and separated external CSS layout strategies.", path: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio/tree/main/01-course-projects/01-video-course-app/01-basic-boilerplate-app", github: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio", techStack: ["React", "JSX", "CSS Modules"], singleGif: { url: "https://raw.githubusercontent.com/rajyabdullah-spec/react-js-mastery-portfolio/main/01-course-projects/01-video-course-app/01-basic-boilerplate-app/src/assets/project-demo.gif" } },
  { name: "World Countries & User Setup Hub", desc: "Advanced application mastering functional hooks (useState, useEffect) and Axios data fetching. Features a custom controlled registration form with instantaneous Live Preview and an isolated scrollable UI layout.", path: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio/tree/main/01-course-projects/01-video-course-app/02-countries-and-form-app", github: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio", techStack: ["React", "Axios", "REST API", "Hooks"], singleGif: { url: "https://raw.githubusercontent.com/rajyabdullah-spec/react-js-mastery-portfolio/main/01-course-projects/01-video-course-app/02-countries-and-form-app/src/assets/project-preview.gif" } },
  { name: "Hacker News Search Engine", desc: "Advanced implementation showcasing Server-side Search using the Hacker News API. Features strict immutability patterns and Conditional Rendering.", path: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio/tree/main/01-course-projects/02-hacker-news-app", github: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio", techStack: ["React", "HackerNews API", "Immutability"], singleGif: { url: "https://raw.githubusercontent.com/rajyabdullah-spec/react-js-mastery-portfolio/main/01-course-projects/02-hacker-news-app/src/assets/project-demo.gif" } },
  { name: "Custom Styled ToDo App", desc: "A responsive task management tracker handling state synchronization across multiple controlled input streams, dynamic filtering, and a custom UI.", path: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio/tree/main/02-assignments/assignment-01", github: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio", techStack: ["React", "State Sync", "Controlled Inputs"], singleGif: { url: "https://raw.githubusercontent.com/rajyabdullah-spec/react-js-mastery-portfolio/main/02-assignments/assignment-01/src/assets/project-demo.gif" } },
  { name: "Inspirational Quotes Generator", desc: "An asynchronous dynamic quotes generator driven by functional states and Axios network integration. Features robust loading/error boundaries to prevent concurrent API flooding and clean isolated CSS typography.", path: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio/tree/main/02-assignments/assignment-02/02-quotes-generator-app", github: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio", techStack: ["React", "Axios", "Async Boundaries"], singleGif: { url: "https://raw.githubusercontent.com/rajyabdullah-spec/react-js-mastery-portfolio/main/02-assignments/assignment-02/02-quotes-generator-app/src/assets/project-demo.gif" } },
  { name: "The Timeline Engine", desc: "Advanced single-page engine utilizing the React Context API to manage complex nested relational state models and bidirectional chronological data streams under a premium custom user interface.", path: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio/tree/main/02-assignments/assignment-03/03-the-timeline-app", github: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio", techStack: ["React", "Context API", "Relational State"], singleGif: { url: "https://raw.githubusercontent.com/rajyabdullah-spec/react-js-mastery-portfolio/main/03-the-timeline-app/src/assets/project-preview.gif" } },
  { name: "Premium Music Engine Challenge", desc: "An asynchronous React application capturing metadata queries and integrating with the live Apple iTunes Search API to render true commercial album catalogs, rich cover arts, and precise control form lifecycles.", path: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio/tree/main/03-demo-challenges/demo-challenge-01", github: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio", techStack: ["React", "iTunes API", "Controlled Forms"], singleGif: { url: "https://raw.githubusercontent.com/rajyabdullah-spec/react-js-mastery-portfolio/main/03-demo-challenges/demo-challenge-01/src/assets/project-preview.gif" } },
  { name: "Reddit Feed & Auto-Sorting Engine", desc: "A dynamic social feed application built with persistent LocalStorage state synchronization, real-time upvote auto-sorting logic, input character limits, and responsive UI card interactions.", path: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio/tree/main/03-demo-challenges/demo-challenge-02", github: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio", techStack: ["React", "LocalStorage", "Auto-Sorting"], singleGif: { url: "https://raw.githubusercontent.com/rajyabdullah-spec/react-js-mastery-portfolio/main/03-demo-challenges/demo-challenge-02/src/assets/demo-preview.gif" } },
  { name: "LinkedIn Wireframe Navigation Challenge", desc: "A multipage SPA implementing precise wireframe route architecture and global state synchronization using React Router DOM v6 and Context API, featuring protected route guards and dynamic member profile rendering.", path: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio/tree/main/03-demo-challenges/demo-challenge-03", github: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio", techStack: ["React 18", "Router v6", "Auth Context"], singleGif: { url: "https://raw.githubusercontent.com/rajyabdullah-spec/react-js-mastery-portfolio/main/03-demo-challenges/demo-challenge-03/src/assets/demo-preview.gif" } },
  { name: "Product Management Dashboard", desc: "High-performance full CRUD application built on React Context API for global state management and React Router DOM v6 for dynamic routing. Features reusable controlled forms, tabular listing with actions, and a pixel-perfect dark UI.", path: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio/tree/main/04-final-capstone/main-react-challenge", github: "https://github.com/rajyabdullah-spec/react-js-mastery-portfolio", techStack: ["React 18", "Full CRUD", "Context API", "Router v6"], singleGif: { url: "https://raw.githubusercontent.com/rajyabdullah-spec/react-js-mastery-portfolio/main/04-final-capstone/main-react-challenge/src/assets/demo-preview.gif" } }
];

const importData = async () => {
  try {
    await connectDB();
    
    console.log('Clearing old projects...');
    await Project.deleteMany();

    const formattedProjects = [
      ...htmlCssProjects.map(p => ({
        title: p.name,
        description: p.desc,
        techStack: p.techStack || [],
        githubUrl: p.github || '',
        liveUrl: p.path || '',
        imageUrl: '',
        subPathUrl: p.github || ''
      })),
      ...jsProjects.map(p => ({
        title: p.name,
        description: p.desc,
        techStack: p.techStack || [],
        githubUrl: p.github || '',
        liveUrl: p.path || '',
        imageUrl: '',
        subPathUrl: p.github || ''
      })),
      ...algoProjects.map(p => ({
        title: p.name,
        description: p.desc,
        techStack: p.techStack || [],
        githubUrl: p.github || '',
        liveUrl: '',
        imageUrl: '',
        subPathUrl: p.path || ''
      })),
      ...ajaxProjects.map(p => ({
        title: p.name,
        description: p.desc,
        techStack: p.techStack || [],
        githubUrl: p.github || '',
        liveUrl: p.path || '',
        imageUrl: '',
        subPathUrl: p.github || ''
      })),
      ...backendProjects.map(p => ({
        title: p.name,
        description: p.desc,
        techStack: p.techStack || [],
        githubUrl: p.github || '',
        liveUrl: p.id === "06" ? p.path : '',
        imageUrl: p.singleGif ? p.singleGif.url : (p.images ? p.images[0] : ''),
        subPathUrl: p.id === "06" ? p.github : (p.path || '')
      })),
      ...reactProjects.map(p => ({
        title: p.name,
        description: p.desc,
        techStack: p.techStack || [],
        githubUrl: p.github || '',
        liveUrl: '',
        imageUrl: p.singleGif ? p.singleGif.url : '',
        subPathUrl: p.path || ''
      }))
    ];

    await Project.insertMany(formattedProjects);
    console.log(`Successfully injected ${formattedProjects.length} structured projects!`);
    
    await mongoose.connection.close();
    process.exit(0);
  } catch (error) {
    console.error(`Import Error: ${error}`);
    process.exit(1);
  }
};

importData();